language: elixir
cache: false
matrix:
  include:
    - node_js: 8.11.1
      before_install:
        - nvm install 8.11.1
        - npm i -g npm
        - npm i -g codecov
      install:
        - cd priv/react_app && npm install
      script:
        - npm run build
        - npm run test-coverage
      after_success:
        - codecov
    - elixir: 1.8.2
      otp_release: 22
      before_install:
        - gem install fakes3
        - fakes3 -r $HOME/.s3bucket -p 4567 --license 9806002125 &
      install:
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get
      script:
        - npm run test-coverage-backend
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      after_script:
        - kill $(pgrep -f fakes3)
