/**
 * This file contains a String for every possible action that can be happen in the application
 */
export default {
	FETCH_COMPANIES_SUCCESS: 'FETCH_COMPANIES_SUCCESS',
	FETCH_COMPANIES_FAILURE: 'FETCH_COMPANIES_FAILURE',
  FETCH_COMPANIES: 'FETCH_COMPANIES',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',

  VERIFY_FORGOT_PASSWORD_KEY_REQUEST: 'VERIFY_FORGOT_PASSWORD_KEY_REQUEST',
  VERIFY_FORGOT_PASSWORD_KEY_SUCCESS: 'VERIFY_FORGOT_PASSWORD_KEY_SUCCESS',
  VERIFY_FORGOT_PASSWORD_KEY_FAILURE: 'VERIFY_FORGOT_PASSWORD_KEY_FAILURE',

  REPLACE_FORGOTTEN_PASSWORD_REQUEST: 'REPLACE_FORGOTTEN_PASSWORD_REQUEST',
  REPLACE_FORGOTTEN_PASSWORD_SUCCESS: 'REPLACE_FORGOTTEN_PASSWORD_SUCCESS',
  REPLACE_FORGOTTEN_PASSWORD_FAILURE: 'REPLACE_FORGOTTEN_PASSWORD_FAILURE',
}
