/**
 * This file contains a String for every possible action that can be happen in the application
 */
export default {
	FETCH_COMPANIES_SUCCESS: 'FETCH_COMPANIES_SUCCESS',
	FETCH_COMPANIES_FAILURE: 'FETCH_COMPANIES_FAILURE',
  FETCH_COMPANIES: 'FETCH_COMPANIES',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',
}
