/**
 * This file contains a String for every possible action that can be happen in the application
 */
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_FAILURE = 'FETCH_COMPANIES_FAILURE';
export const FETCH_COMPANIES = 'FETCH_COMPANIES';

export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS';
export const FETCH_COMPANY_FAILURE = 'FETCH_COMPANY_FAILURE';
export const FETCH_COMPANY = 'FETCH_COMPANY';

export const POST_COMPANY_SUCCESS = 'POST_COMPANY_SUCCESS';
export const POST_COMPANY_FAILURE = 'POST_COMPANY_FAILURE';
export const POST_COMPANY = 'POST_COMPANY';

export const POST_COMPANY_BULK_SUCCESS = 'POST_COMPANY_BULK_SUCCESS';
export const POST_COMPANY_BULK_FAILURE = 'POST_COMPANY_BULK_FAILURE';
export const POST_COMPANY_BULK = 'POST_COMPANY_BULK';

export const PUT_COMPANY_SUCCESS = 'PUT_COMPANY_SUCCESS';
export const PUT_COMPANY_FAILURE = 'PUT_COMPANY_FAILURE';
export const PUT_COMPANY = 'PUT_COMPANY';

export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_FAILURE = 'DELETE_COMPANY_FAILURE';
export const DELETE_COMPANY = 'DELETE_COMPANY';

export const FETCH_DEADLINES_SUCCESS = 'FETCH_DEADLINES_SUCCESS';
export const FETCH_DEADLINES_FAILURE = 'FETCH_DEADLINES_FAILURE';
export const FETCH_DEADLINES = 'FETCH_DEADLINES';

export const FETCH_DEADLINE_SUCCESS = 'FETCH_DEADLINE_SUCCESS';
export const FETCH_DEADLINE_FAILURE = 'FETCH_DEADLINE_FAILURE';
export const FETCH_DEADLINE = 'FETCH_DEADLINE';

export const POST_DEADLINE_SUCCESS = 'POST_DEADLINE_SUCCESS';
export const POST_DEADLINE_FAILURE = 'POST_DEADLINE_FAILURE';
export const POST_DEADLINE = 'POST_DEADLINE';

export const PUT_DEADLINE_SUCCESS = 'PUT_DEADLINE_SUCCESS';
export const PUT_DEADLINE_FAILURE = 'PUT_DEADLINE_FAILURE';
export const PUT_DEADLINE = 'PUT_DEADLINE';

export const DELETE_DEADLINE_SUCCESS = 'DELETE_DEADLINE_SUCCESS';
export const DELETE_DEADLINE_FAILURE = 'DELETE_DEADLINE_FAILURE';
export const DELETE_DEADLINE = 'DELETE_DEADLINE';

export const FETCH_MAILTEMPLATES_SUCCESS = 'FETCH_MAILTEMPLATES_SUCCESS';
export const FETCH_MAILTEMPLATES_FAILURE = 'FETCH_MAILTEMPLATES_FAILURE';
export const FETCH_MAILTEMPLATES = 'FETCH_MAILTEMPLATES';

export const FETCH_MAILTEMPLATE_SUCCESS = 'FETCH_MAILTEMPLATE_SUCCESS';
export const FETCH_MAILTEMPLATE_FAILURE = 'FETCH_MAILTEMPLATE_FAILURE';
export const FETCH_MAILTEMPLATE = 'FETCH_MAILTEMPLATE';

export const POST_MAILTEMPLATE_SUCCESS = 'POST_MAILTEMPLATE_SUCCESS';
export const POST_MAILTEMPLATE_FAILURE = 'POST_MAILTEMPLATE_FAILURE';
export const POST_MAILTEMPLATE = 'POST_MAILTEMPLATE';

export const PUT_MAILTEMPLATE_SUCCESS = 'PUT_MAILTEMPLATE_SUCCESS';
export const PUT_MAILTEMPLATE_FAILURE = 'PUT_MAILTEMPLATE_FAILURE';
export const PUT_MAILTEMPLATE = 'PUT_MAILTEMPLATE';

export const DELETE_MAILTEMPLATE_SUCCESS = 'DELETE_MAILTEMPLATE_SUCCESS';
export const DELETE_MAILTEMPLATE_FAILURE = 'DELETE_MAILTEMPLATE_FAILURE';
export const DELETE_MAILTEMPLATE = 'DELETE_MAILTEMPLATE';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';

export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_FAILURE = 'POST_CATEGORY_FAILURE';
export const POST_CATEGORY = 'POST_CATEGORY';

export const PUT_CATEGORY_SUCCESS = 'PUT_CATEGORY_SUCCESS';
export const PUT_CATEGORY_FAILURE = 'PUT_CATEGORY_FAILURE';
export const PUT_CATEGORY = 'PUT_CATEGORY';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const FETCH_PROGRAMMES_SUCCESS = 'FETCH_PROGRAMMES_SUCCESS';
export const FETCH_PROGRAMMES_FAILURE = 'FETCH_PROGRAMMES_FAILURE';
export const FETCH_PROGRAMMES = 'FETCH_PROGRAMMES';

export const FETCH_PROGRAMME_SUCCESS = 'FETCH_PROGRAMME_SUCCESS';
export const FETCH_PROGRAMME_FAILURE = 'FETCH_PROGRAMME_FAILURE';
export const FETCH_PROGRAMME = 'FETCH_PROGRAMME';

export const POST_PROGRAMME_SUCCESS = 'POST_PROGRAMME_SUCCESS';
export const POST_PROGRAMME_FAILURE = 'POST_PROGRAMME_FAILURE';
export const POST_PROGRAMME = 'POST_PROGRAMME';

export const PUT_PROGRAMME_SUCCESS = 'PUT_PROGRAMME_SUCCESS';
export const PUT_PROGRAMME_FAILURE = 'PUT_PROGRAMME_FAILURE';
export const PUT_PROGRAMME = 'PUT_PROGRAMME';

export const DELETE_PROGRAMME_SUCCESS = 'DELETE_PROGRAMME_SUCCESS';
export const DELETE_PROGRAMME_FAILURE = 'DELETE_PROGRAMME_FAILURE';
export const DELETE_PROGRAMME = 'DELETE_PROGRAMME';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';
export const FETCH_ROLES = 'FETCH_ROLES';

export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE';
export const FETCH_ROLE = 'FETCH_ROLE';

export const POST_ROLE_SUCCESS = 'POST_ROLE_SUCCESS';
export const POST_ROLE_FAILURE = 'POST_ROLE_FAILURE';
export const POST_ROLE = 'POST_ROLE';

export const PUT_ROLE_SUCCESS = 'PUT_ROLE_SUCCESS';
export const PUT_ROLE_FAILURE = 'PUT_ROLE_FAILURE';
export const PUT_ROLE = 'PUT_ROLE';

export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';
export const DELETE_ROLE = 'DELETE_ROLE';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';

export const PUT_CURRENT_USER = 'PUT_CURRENT_USER';
export const PUT_CURRENT_USER_SUCCESS = 'PUT_CURRENT_USER_SUCCESS';
export const PUT_CURRENT_USER_FAILURE = 'PUT_CURRENT_USER_FAILURE';

export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER';
export const DELETE_CURRENT_USER_SUCCESS = 'DELETE_CURRENT_USER_SUCCESS';
export const DELETE_CURRENT_USER_FAILURE = 'DELETE_CURRENT_USER_FAILURE';

export const PUT_CURRENT_STUDENT = 'PUT_CURRENT_STUDENT';
export const PUT_CURRENT_STUDENT_SUCCESS = 'PUT_CURRENT_STUDENT_SUCCESS';
export const PUT_CURRENT_STUDENT_FAILURE = 'PUT_CURRENT_STUDENT_FAILURE';

export const FETCH_CURRENT_COMPANY = 'FETCH_CURRENT_COMPANY';
export const FETCH_CURRENT_COMPANY_SUCCESS = 'FETCH_CURRENT_COMPANY_SUCCESS';
export const FETCH_CURRENT_COMPANY_FAILURE = 'FETCH_CURRENT_COMPANY_FAILURE';

export const PUT_CURRENT_COMPANY = 'PUT_CURRENT_COMPANY';
export const PUT_CURRENT_COMPANY_SUCCESS = 'PUT_CURRENT_COMPANY_SUCCESS';
export const PUT_CURRENT_COMPANY_FAILURE = 'PUT_CURRENT_COMPANY_FAILURE';

export const DELETE_CURRENT_COMPANY = 'DELETE_CURRENT_COMPANY';
export const DELETE_CURRENT_COMPANY_SUCCESS = 'DELETE_CURRENT_COMPANY_SUCCESS';
export const DELETE_CURRENT_COMPANY_FAILURE = 'DELETE_CURRENT_COMPANY_FAILURE';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER = 'FETCH_USER';

export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_FAILURE = 'POST_USER_FAILURE';
export const POST_USER = 'POST_USER';

export const PUT_USER_SUCCESS = 'PUT_USER_SUCCESS';
export const PUT_USER_FAILURE = 'PUT_USER_FAILURE';
export const PUT_USER = 'PUT_USER';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const DELETE_USER = 'DELETE_USER';

export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';

export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAILURE = 'FETCH_STUDENT_FAILURE';
export const FETCH_STUDENT = 'FETCH_STUDENT';

export const POST_STUDENT_SUCCESS = 'POST_STUDENT_SUCCESS';
export const POST_STUDENT_FAILURE = 'POST_STUDENT_FAILURE';
export const POST_STUDENT = 'POST_STUDENT';

export const PUT_STUDENT_SUCCESS = 'PUT_STUDENT_SUCCESS';
export const PUT_STUDENT_FAILURE = 'PUT_STUDENT_FAILURE';
export const PUT_STUDENT = 'PUT_STUDENT';

export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';
export const DELETE_STUDENT = 'DELETE_STUDENT';

export const POST_STUDENT_SESSION_APPL_SUCCESS =
  'POST_STUDENT_SESSION_APPL_SUCCESS';
export const POST_STUDENT_SESSION_APPL_FAILURE =
  'POST_STUDENT_SESSION_APPL_FAILURE';
export const POST_STUDENT_SESSION_APPL = 'POST_STUDENT_SESSION_APPL';

export const PUT_STUDENT_SESSION_APPL_SUCCESS =
  'PUT_STUDENT_SESSION_APPL_SUCCESS';
export const PUT_STUDENT_SESSION_APPL_FAILURE =
  'PUT_STUDENT_SESSION_APPL_FAILURE';
export const PUT_STUDENT_SESSION_APPL = 'PUT_STUDENT_SESSION_APPL';

export const DELETE_STUDENT_SESSION_APPL_SUCCESS =
  'DELETE_STUDENT_SESSION_APPL_SUCCESS';
export const DELETE_STUDENT_SESSION_APPL_FAILURE =
  'DELETE_STUDENT_SESSION_APPL_FAILURE';
export const DELETE_STUDENT_SESSION_APPL = 'DELETE_STUDENT_SESSION_APPL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const VERIFY_FORGOT_PASSWORD_KEY_REQUEST =
  'VERIFY_FORGOT_PASSWORD_KEY_REQUEST';
export const VERIFY_FORGOT_PASSWORD_KEY_SUCCESS =
  'VERIFY_FORGOT_PASSWORD_KEY_SUCCESS';
export const VERIFY_FORGOT_PASSWORD_KEY_FAILURE =
  'VERIFY_FORGOT_PASSWORD_KEY_FAILURE';

export const POST_STUDENT_SESSION_SUCCESS = 'POST_STUDENT_SESSION_SUCCESS';
export const POST_STUDENT_SESSION_FAILURE = 'POST_STUDENT_SESSION_FAILURE';
export const POST_STUDENT_SESSION = 'POST_STUDENT_SESSION';

export const PUT_STUDENT_SESSION_SUCCESS = 'PUT_STUDENT_SESSION_SUCCESS';
export const PUT_STUDENT_SESSION_FAILURE = 'PUT_STUDENT_SESSION_FAILURE';
export const PUT_STUDENT_SESSION = 'PUT_STUDENT_SESSION';

export const DELETE_STUDENT_SESSION_SUCCESS = 'DELETE_STUDENT_SESSION_SUCCESS';
export const DELETE_STUDENT_SESSION_FAILURE = 'DELETE_STUDENT_SESSION_FAILURE';
export const DELETE_STUDENT_SESSION = 'DELETE_STUDENT_SESSION';

export const POST_BULK_STUDENT_SESSION_SUCCESS =
  'POST_BULK_STUDENT_SESSION_SUCCESS';
export const POST_BULK_STUDENT_SESSION_FAILURE =
  'POST_BULK_STUDENT_SESSION_FAILURE';
export const POST_BULK_STUDENT_SESSION = 'POST_BULK_STUDENT_SESSION';

export const REPLACE_FORGOTTEN_PASSWORD_REQUEST =
  'REPLACE_FORGOTTEN_PASSWORD_REQUEST';
export const REPLACE_FORGOTTEN_PASSWORD_SUCCESS =
  'REPLACE_FORGOTTEN_PASSWORD_SUCCESS';
export const REPLACE_FORGOTTEN_PASSWORD_FAILURE =
  'REPLACE_FORGOTTEN_PASSWORD_FAILURE';

export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
export const FETCH_STATISTICS_FAILURE = 'FETCH_STATISTICS_FAILURE';
export const FETCH_STATISTICS = 'FETCH_STATISTICS';
