/**
 * This file contains a String for every possible action that can be happen in the application
 */
export default {
  FETCH_COMPANIES_SUCCESS: 'FETCH_COMPANIES_SUCCESS',
  FETCH_COMPANIES_FAILURE: 'FETCH_COMPANIES_FAILURE',
  FETCH_COMPANIES: 'FETCH_COMPANIES',

  FETCH_COMPANY_SUCCESS: 'FETCH_COMPANY_SUCCESS',
  FETCH_COMPANY_FAILURE: 'FETCH_COMPANY_FAILURE',
  FETCH_COMPANY: 'FETCH_COMPANY',

  POST_COMPANY_SUCCESS: 'POST_COMPANY_SUCCESS',
  POST_COMPANY_FAILURE: 'POST_COMPANY_FAILURE',
  POST_COMPANY: 'POST_COMPANY',

  PUT_COMPANY_SUCCESS: 'PUT_COMPANY_SUCCESS',
  PUT_COMPANY_FAILURE: 'PUT_COMPANY_FAILURE',
  PUT_COMPANY: 'PUT_COMPANY',

  DELETE_COMPANY_SUCCESS: 'DELETE_COMPANY_SUCCESS',
  DELETE_COMPANY_FAILURE: 'DELETE_COMPANY_FAILURE',
  DELETE_COMPANY: 'DELETE_COMPANY',

  FETCH_DEADLINES_SUCCESS: 'FETCH_DEADLINES_SUCCESS',
  FETCH_DEADLINES_FAILURE: 'FETCH_DEADLINES_FAILURE',
  FETCH_DEADLINES: 'FETCH_DEADLINES',

  FETCH_DEADLINE_SUCCESS: 'FETCH_DEADLINE_SUCCESS',
  FETCH_DEADLINE_FAILURE: 'FETCH_DEADLINE_FAILURE',
  FETCH_DEADLINE: 'FETCH_DEADLINE',

  POST_DEADLINE_SUCCESS: 'POST_DEADLINE_SUCCESS',
  POST_DEADLINE_FAILURE: 'POST_DEADLINE_FAILURE',
  POST_DEADLINE: 'POST_DEADLINE',

  PUT_DEADLINE_SUCCESS: 'PUT_DEADLINE_SUCCESS',
  PUT_DEADLINE_FAILURE: 'PUT_DEADLINE_FAILURE',
  PUT_DEADLINE: 'PUT_DEADLINE',

  DELETE_DEADLINE_SUCCESS: 'DELETE_DEADLINE_SUCCESS',
  DELETE_DEADLINE_FAILURE: 'DELETE_DEADLINE_FAILURE',
  DELETE_DEADLINE: 'DELETE_DEADLINE',

  FETCH_MAILTEMPLATES_SUCCESS: 'FETCH_MAILTEMPLATES_SUCCESS',
  FETCH_MAILTEMPLATES_FAILURE: 'FETCH_MAILTEMPLATES_FAILURE',
  FETCH_MAILTEMPLATES: 'FETCH_MAILTEMPLATES',

  FETCH_MAILTEMPLATE_SUCCESS: 'FETCH_MAILTEMPLATE_SUCCESS',
  FETCH_MAILTEMPLATE_FAILURE: 'FETCH_MAILTEMPLATE_FAILURE',
  FETCH_MAILTEMPLATE: 'FETCH_MAILTEMPLATE',

  POST_MAILTEMPLATE_SUCCESS: 'POST_MAILTEMPLATE_SUCCESS',
  POST_MAILTEMPLATE_FAILURE: 'POST_MAILTEMPLATE_FAILURE',
  POST_MAILTEMPLATE: 'POST_MAILTEMPLATE',

  PUT_MAILTEMPLATE_SUCCESS: 'PUT_MAILTEMPLATE_SUCCESS',
  PUT_MAILTEMPLATE_FAILURE: 'PUT_MAILTEMPLATE_FAILURE',
  PUT_MAILTEMPLATE: 'PUT_MAILTEMPLATE',

  DELETE_MAILTEMPLATE_SUCCESS: 'DELETE_MAILTEMPLATE_SUCCESS',
  DELETE_MAILTEMPLATE_FAILURE: 'DELETE_MAILTEMPLATE_FAILURE',
  DELETE_MAILTEMPLATE: 'DELETE_MAILTEMPLATE',

  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',

  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',
  FETCH_CATEGORY: 'FETCH_CATEGORY',

  POST_CATEGORY_SUCCESS: 'POST_CATEGORY_SUCCESS',
  POST_CATEGORY_FAILURE: 'POST_CATEGORY_FAILURE',
  POST_CATEGORY: 'POST_CATEGORY',

  PUT_CATEGORY_SUCCESS: 'PUT_CATEGORY_SUCCESS',
  PUT_CATEGORY_FAILURE: 'PUT_CATEGORY_FAILURE',
  PUT_CATEGORY: 'PUT_CATEGORY',

  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  FETCH_PROGRAMMES_SUCCESS: 'FETCH_PROGRAMMES_SUCCESS',
  FETCH_PROGRAMMES_FAILURE: 'FETCH_PROGRAMMES_FAILURE',
  FETCH_PROGRAMMES: 'FETCH_PROGRAMMES',

  FETCH_PROGRAMME_SUCCESS: 'FETCH_PROGRAMME_SUCCESS',
  FETCH_PROGRAMME_FAILURE: 'FETCH_PROGRAMME_FAILURE',
  FETCH_PROGRAMME: 'FETCH_PROGRAMME',

  POST_PROGRAMME_SUCCESS: 'POST_PROGRAMME_SUCCESS',
  POST_PROGRAMME_FAILURE: 'POST_PROGRAMME_FAILURE',
  POST_PROGRAMME: 'POST_PROGRAMME',

  PUT_PROGRAMME_SUCCESS: 'PUT_PROGRAMME_SUCCESS',
  PUT_PROGRAMME_FAILURE: 'PUT_PROGRAMME_FAILURE',
  PUT_PROGRAMME: 'PUT_PROGRAMME',

  DELETE_PROGRAMME_SUCCESS: 'DELETE_PROGRAMME_SUCCESS',
  DELETE_PROGRAMME_FAILURE: 'DELETE_PROGRAMME_FAILURE',
  DELETE_PROGRAMME: 'DELETE_PROGRAMME',


  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  FETCH_ROLES_SUCCESS: 'FETCH_ROLES_SUCCESS',
  FETCH_ROLES_FAILURE: 'FETCH_ROLES_FAILURE',
  FETCH_ROLES: 'FETCH_ROLES',

  FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
  FETCH_ROLE_FAILURE: 'FETCH_ROLE_FAILURE',
  FETCH_ROLE: 'FETCH_ROLE',

  POST_ROLE_SUCCESS: 'POST_ROLE_SUCCESS',
  POST_ROLE_FAILURE: 'POST_ROLE_FAILURE',
  POST_ROLE: 'POST_ROLE',

  PUT_ROLE_SUCCESS: 'PUT_ROLE_SUCCESS',
  PUT_ROLE_FAILURE: 'PUT_ROLE_FAILURE',
  PUT_ROLE: 'PUT_ROLE',

  DELETE_ROLE_SUCCESS: 'DELETE_ROLE_SUCCESS',
  DELETE_ROLE_FAILURE: 'DELETE_ROLE_FAILURE',
  DELETE_ROLE: 'DELETE_ROLE',

  FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',

  PUT_CURRENT_USER: 'PUT_CURRENT_USER',
  PUT_CURRENT_USER_SUCCESS: 'PUT_CURRENT_USER_SUCCESS',
  PUT_CURRENT_USER_FAILURE: 'PUT_CURRENT_USER_FAILURE',

  DELETE_CURRENT_USER: 'DELETE_CURRENT_USER',
  DELETE_CURRENT_USER_SUCCESS: 'DELETE_CURRENT_USER_SUCCESS',
  DELETE_CURRENT_USER_FAILURE: 'DELETE_CURRENT_USER_FAILURE',

  PUT_CURRENT_STUDENT: 'PUT_CURRENT_STUDENT',
  PUT_CURRENT_STUDENT_SUCCESS: 'PUT_CURRENT_STUDENT_SUCCESS',
  PUT_CURRENT_STUDENT_FAILURE: 'PUT_CURRENT_STUDENT_FAILURE',

  FETCH_CURRENT_COMPANY: 'FETCH_CURRENT_COMPANY',
  FETCH_CURRENT_COMPANY_SUCCESS: 'FETCH_CURRENT_COMPANY_SUCCESS',
  FETCH_CURRENT_COMPANY_FAILURE: 'FETCH_CURRENT_COMPANY_FAILURE',

  PUT_CURRENT_COMPANY: 'PUT_CURRENT_COMPANY',
  PUT_CURRENT_COMPANY_SUCCESS: 'PUT_CURRENT_COMPANY_SUCCESS',
  PUT_CURRENT_COMPANY_FAILURE: 'PUT_CURRENT_COMPANY_FAILURE',

  DELETE_CURRENT_COMPANY: 'DELETE_CURRENT_COMPANY',
  DELETE_CURRENT_COMPANY_SUCCESS: 'DELETE_CURRENT_COMPANY_SUCCESS',
  DELETE_CURRENT_COMPANY_FAILURE: 'DELETE_CURRENT_COMPANY_FAILURE',

  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  FETCH_USERS: 'FETCH_USERS',

  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
  FETCH_USER: 'FETCH_USER',

  POST_USER_SUCCESS: 'POST_USER_SUCCESS',
  POST_USER_FAILURE: 'POST_USER_FAILURE',
  POST_USER: 'POST_USER',

  PUT_USER_SUCCESS: 'PUT_USER_SUCCESS',
  PUT_USER_FAILURE: 'PUT_USER_FAILURE',
  PUT_USER: 'PUT_USER',

  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
  DELETE_USER: 'DELETE_USER',

  FETCH_STUDENTS_SUCCESS: 'FETCH_STUDENTS_SUCCESS',
  FETCH_STUDENTS_FAILURE: 'FETCH_STUDENTS_FAILURE',
  FETCH_STUDENTS: 'FETCH_STUDENTS',

  FETCH_STUDENT_SUCCESS: 'FETCH_STUDENT_SUCCESS',
  FETCH_STUDENT_FAILURE: 'FETCH_STUDENT_FAILURE',
  FETCH_STUDENT: 'FETCH_STUDENT',

  POST_STUDENT_SUCCESS: 'POST_STUDENT_SUCCESS',
  POST_STUDENT_FAILURE: 'POST_STUDENT_FAILURE',
  POST_STUDENT: 'POST_STUDENT',

  PUT_STUDENT_SUCCESS: 'PUT_STUDENT_SUCCESS',
  PUT_STUDENT_FAILURE: 'PUT_STUDENT_FAILURE',
  PUT_STUDENT: 'PUT_STUDENT',

  DELETE_STUDENT_SUCCESS: 'DELETE_STUDENT_SUCCESS',
  DELETE_STUDENT_FAILURE: 'DELETE_STUDENT_FAILURE',
  DELETE_STUDENT: 'DELETE_STUDENT',

  POST_STUDENT_SESSION_APPL_SUCCESS: 'POST_STUDENT_SESSION_APPL_SUCCESS',
  POST_STUDENT_SESSION_APPL_FAILURE: 'POST_STUDENT_SESSION_APPL_FAILURE',
  POST_STUDENT_SESSION_APPL: 'POST_STUDENT_SESSION_APPL',

  PUT_STUDENT_SESSION_APPL_SUCCESS: 'PUT_STUDENT_SESSION_APPL_SUCCESS',
  PUT_STUDENT_SESSION_APPL_FAILURE: 'PUT_STUDENT_SESSION_APPL_FAILURE',
  PUT_STUDENT_SESSION_APPL: 'PUT_STUDENT_SESSION_APPL',

  DELETE_STUDENT_SESSION_APPL_SUCCESS: 'DELETE_STUDENT_SESSION_APPL_SUCCESS',
  DELETE_STUDENT_SESSION_APPL_FAILURE: 'DELETE_STUDENT_SESSION_APPL_FAILURE',
  DELETE_STUDENT_SESSION_APPL: 'DELETE_STUDENT_SESSION_APPL',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',

  VERIFY_FORGOT_PASSWORD_KEY_REQUEST: 'VERIFY_FORGOT_PASSWORD_KEY_REQUEST',
  VERIFY_FORGOT_PASSWORD_KEY_SUCCESS: 'VERIFY_FORGOT_PASSWORD_KEY_SUCCESS',
  VERIFY_FORGOT_PASSWORD_KEY_FAILURE: 'VERIFY_FORGOT_PASSWORD_KEY_FAILURE',

  REPLACE_FORGOTTEN_PASSWORD_REQUEST: 'REPLACE_FORGOTTEN_PASSWORD_REQUEST',
  REPLACE_FORGOTTEN_PASSWORD_SUCCESS: 'REPLACE_FORGOTTEN_PASSWORD_SUCCESS',
  REPLACE_FORGOTTEN_PASSWORD_FAILURE: 'REPLACE_FORGOTTEN_PASSWORD_FAILURE',

  FETCH_STATISTICS_SUCCESS: 'FETCH_STATISTICS_SUCCESS',
  FETCH_STATISTICS_FAILURE: 'FETCH_STATISTICS_FAILURE',
  FETCH_STATISTICS: 'FETCH_STATISTICS'
};
